version: '3.8'

volumes:
  test_volume:

services:
  postgres:
    image: postgres:latest
    container_name: assignment-postgres
    volumes:
      - test_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=assignment8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
